TARGET = SidechainCompressor

CPP_SOURCES = TestSidechainCompressor.cpp

LIBDAISY_DIR = ../../libDaisy/
DAISYSP_DIR = ../../DaisySP/
JAMES_DIR = ../../JamesClasses/

C_INCLUDES += -I$(JAMES_DIR)

SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile	